### ISSUE TITLE
load_model() fails when .nlogo file includes NetLogo extensions

### ISSUE THREAD

**Issue by brendenpetersen** [quaquel/pyNetLogo#15]
Hi, I'm new to this project but am very excited about it. I'm having trouble loading models that require a built-in extension. I've ensured that I do have these extensions, e.g.:

```
$ ls /Applications/NetLogo\ 5.3.1/extensions/sound/
sound.jar
```

I can also open and run models with no issues by double-clicking the .nlogo file.

Here is a minimal example:

```
import pyNetLogo
netlogo = pyNetLogo.NetLogoLink(gui=False, netlogo_home="/Applications/NetLogo 5.3.1/")
netlogo.load_model("/Users/.../model.nlogo")
```

The last line yields the error:

```
java.lang.IllegalStateException: Can't find extension: sound/sound.jar
	at org.nlogo.workspace.ExtensionManager.resolvePathAsURL(ExtensionManager.java:315)
	at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.java:153)
	at org.nlogo.compiler.StructureParser.parseImport(StructureParser.scala:459)
	at org.nlogo.compiler.StructureParser.parse(StructureParser.scala:196)
	at org.nlogo.compiler.CompilerMain$.compile(CompilerMain.scala:25)
	at org.nlogo.compiler.Compiler$.compileProgram(Compiler.scala:28)
	at org.nlogo.headless.HeadlessModelOpener.openFromMap(HeadlessModelOpener.scala:53)
	at org.nlogo.headless.HeadlessWorkspace.openString(HeadlessWorkspace.scala:531)
	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:513)
	at NetLogoLinkV5.NetLogoLink.loadModel(Unknown Source)
Traceback (most recent call last):
  File "/Users/.../lib/python3.6/site-packages/pyNetLogo/core.py", line 253, in load_model
    self.link.loadModel(path)
jpype._jexception.CompilerExceptionPyRaisable: Can't find extension: sound at position 12 in 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../lib/python3.6/site-packages/pyNetLogo/core.py", line 255, in load_model
    raise NetLogoException(ex.message())
pyNetLogo.core.NetLogoException: Can't find extension: sound
```

This occurs when loading a model with any extensions found in my NetLogo path, `/Applications/NetLogo\ 5.3.1/extensions`.

Is anyone able to help? I've found similar issues before (related to running NetLogo--usually in headless mode--but unrelated to this package), e.g. [here](https://github.com/rcgsheffield/sheffield_hpc/issues/390) and [here](http://netlogo-users.18673.x6.nabble.com/Extensions-in-Headless-mode-td4865994.html). Thanks!

**Comment by brendenpetersen** [comment]
Well, that was a short-lived problem!

I simply created a symbolic link from the NetLogo `extensions` directory to the directory from which I ran my script.

It would be great if anyone has a better explanation, since I'll eventually be using these scripts as part of a Python package that will be distributed across multiple nodes and/or called from elsewhere.

**Comment by quaquel** [comment]
The problem you describe has been fixed in master, which I hope to turn into a new release for pip before the end of the year

**Comment by brendenpetersen** [comment]
Ah, thanks! Yes, I was using the pip release. I guess that also explains why I couldn't find `report_while` and other methods from the documentation. I'll switch from the pip release to Git.

**Comment by quaquel** [comment]
a new release is now available on pip that should fix this issue
