### ISSUE TITLE
Different library loading behavior between interactive shell and batch job

### ISSUE THREAD

**Issue by j3mdamas** [quaquel/pyNetLogo#44]
Hi,
I will try to be simple in explaining my issue. I am using CentOS 7, I have installed NetLogo 5.3.1 (older version is a requirement of the end-user) and PyNetLogo 0.4.2 under Python 3.7.9. All 64 bits.
I was quite happy when I was able to run the software using the following python script based on the example in the documentation:
```python
import os
import pyNetLogo
print(os.environ['NETLOGO_HOME'])
print(os.environ['NETLOGO_VERSION'])
netlogo = pyNetLogo.NetLogoLink(netlogo_home=os.environ['NETLOGO_HOME'], netlogo_version=os.environ['NETLOGO_VERSION'])
netlogo.load_model('./Wolf Sheep Predation_v6.nlogo')
netlogo.command('setup')
counts = netlogo.repeat_report(['count wolves','count sheep'], 200, go='go')
counts.to_csv('tmp.out')
netlogo.kill_workspace()
exit()
```
This was run on a login shell. But I am interested in running it, unattended, on the cluster using a job scheduler (in this case, Altair Grid Engine).

When trying to run it through a batch job on that scheduler, the same example using the same software fails with:
```
Traceback (most recent call last):
  File "NetLogoLink.java", line 76, in NetLogoLinkV5.NetLogoLink.<init>
  File "HeadlessWorkspace.scala", line -1, in org.nlogo.headless.HeadlessWorkspace.newInstance
  File "HeadlessWorkspace.scala", line 31, in org.nlogo.headless.HeadlessWorkspace$.newInstance
  File "HeadlessWorkspace.scala", line 39, in org.nlogo.headless.HeadlessWorkspace$.newInstance
  File "Pico.scala", line 23, in org.nlogo.util.Pico.addScalaObject
  File "Class.java", line 315, in java.lang.Class.forName
  File "Class.java", line -2, in java.lang.Class.forName0
  File "Compiler.scala", line -1, in org.nlogo.compiler.Compiler$.<clinit>
  File "Compiler.scala", line 16, in org.nlogo.compiler.Compiler$.<init>
  File "Femto.scala", line 19, in org.nlogo.util.Femto$.scalaSingleton
  File "Class.java", line 315, in java.lang.Class.forName
  File "Class.java", line -2, in java.lang.Class.forName0
  File "Tokenizer.scala", line -1, in org.nlogo.lex.Tokenizer2D$.<clinit>
  File "Tokenizer.scala", line 7, in org.nlogo.lex.Tokenizer2D$.<init>
  File "TokenMapper.scala", line -1, in org.nlogo.lex.TokenMapper2D$.<clinit>
  File "TokenMapper.scala", line 9, in org.nlogo.lex.TokenMapper2D$.<init>
  File "TokenMapper.scala", line 32, in org.nlogo.lex.TokenMapper.<init>
  File "Color.scala", line -1, in org.nlogo.api.Color$.<clinit>
  File "Color.scala", line 68, in org.nlogo.api.Color$.<init>
  File "ArrayOps.scala", line 38, in scala.collection.mutable.ArrayOps.map
  File "TraversableLike.scala", line 233, in scala.collection.TraversableLike$class.map
  File "ArrayOps.scala", line 38, in scala.collection.mutable.ArrayOps.foreach
  File "IndexedSeqOptimized.scala", line 34, in scala.collection.IndexedSeqOptimized$class.foreach
  File "TraversableLike.scala", line 233, in scala.collection.TraversableLike$$anonfun$map$1.apply
  File "TraversableLike.scala", line 233, in scala.collection.TraversableLike$$anonfun$map$1.apply
  File "Color.scala", line 68, in org.nlogo.api.Color$$anonfun$3.apply
  File "Color.scala", line 69, in org.nlogo.api.Color$$anonfun$3.apply
  File "Color.java", line 275, in java.awt.Color.<clinit>
  File "Toolkit.java", line 1429, in java.awt.Toolkit.<clinit>
  File "Toolkit.java", line 1396, in java.awt.Toolkit.loadLibraries
  File "AccessController.java", line -2, in java.security.AccessController.doPrivileged
  File "Toolkit.java", line 1397, in java.awt.Toolkit$3.run
  File "Toolkit.java", line 1399, in java.awt.Toolkit$3.run
  File "System.java", line 1867, in java.lang.System.loadLibrary
  File "Runtime.java", line 829, in java.lang.Runtime.loadLibrary0
  File "ClassLoader.java", line 2638, in java.lang.ClassLoader.loadLibrary
  File "ClassLoader.java", line 2684, in java.lang.ClassLoader.loadLibrary0
  File "ClassLoader.java", line 2487, in java.lang.ClassLoader$NativeLibrary.loadLibrary
  File "ClassLoader.java", line 2430, in java.lang.ClassLoader$NativeLibrary.load
  File "ClassLoader.java", line -2, in java.lang.ClassLoader$NativeLibrary.load0
  File "System.java", line 1831, in java.lang.System.load
  File "Runtime.java", line 767, in java.lang.Runtime.load0
  File "ClassLoader.java", line 2620, in java.lang.ClassLoader.loadLibrary
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example.py", line 5, in <module>
    netlogo = pyNetLogo.NetLogoLink(netlogo_home=os.environ['NETLOGO_HOME'], netlogo_version=os.environ['NETLOGO_VERSION'])
  File "/progs/all/opensource/pynetlogo/0.4.2/lib/python3.7/site-packages/pyNetLogo/core.py", line 286, in __init__
    jpype.java.lang.Boolean(thd))
java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-11.0.ea.28-7.el7.x86_64/lib/libawt_xawt.so
```
My impression is that, instead of using the runtime libraries that can be found on the `/runtime/lib` of NetLogo, it is trying to use the Java runtime libraries of the OS. Since I am passing the location of NetLogo to `netlogo_home` and it worked in the interactive shell mode, I do not not know what I may be missing.

Have you seen any issue like this before?

**Comment by quaquel** [comment]
pynetlogy depends on jpype. Jpype defaults to JAVA_HOME. 

you can pass a ivm_home kwarg instead to control which ivm is being used.

note that the documentation is slightly incorrect. You need to pass the full path to the jvm you want to use, so in your case a path ending with an *.so file.

**Comment by j3mdamas** [comment]
Thanks. I set the `jvm_home` to `/runtime/lib/amd64/server/libjvm.so` of NetLogo and it worked. Since NetLogo is distributed with it's own Java, I was expecting that when I passed the location of netlogo through `netlogo_home`, that the location of the Java from NetLogo would be inferred from it.
Thanks a lot for your quick help!

**Comment by quaquel** [comment]
At least in the past, on Mac OS, pynetlogo did not come with its own ivm, hence the choice to default to JAVA_HOME.

**Comment by j3mdamas** [comment]
OK, thanks. I am biased by what I see right now and by Linux ;)
