### ISSUE TITLE
Bundled extensions are in `extensions/.bundled` directory

### ISSUE THREAD

**Issue by EwoutH** [quaquel/pyNetLogo#62]
I currently get a warning that the extensions could not be found, and immediately a popup request to install when running `netlogo.load_model()`.
```
UserWarning: could not find default NetLogo extensions folder. Extensions not available
```
(Windows 11 x64, Python 3.11, NetLogo 6.3.0, pyNetLogo@master)

I expect that this was caused due to a change in https://github.com/NetLogo/NetLogo/pull/1716, which puts the bundled extensions in `extensions/.bundled`. [These lines](https://github.com/quaquel/pyNetLogo/blob/55431ddb3c75c5dec41855fca874fbc7e9034ce1/pyNetLogo/core.py#L257-L265) in core.py should probably be updated to reflect those changes.

This [change](https://github.com/NetLogo/NetLogo/commit/1f3298cf2468e9a37e2873051151233a0b9c8b40) affects NetLogo [6.1.0-RC1](https://github.com/NetLogo/NetLogo/releases/tag/6.1.0-RC1) and above.

![Screenshot_73](https://user-images.githubusercontent.com/15776622/214697470-c08ba034-3f87-4662-8635-ffd2aad4a151.png)

**Comment by quaquel** [comment]
Thanks for checking. 

It becomes a pain to manage this range of NetLogo versions and their differences. I am inclined to move towards supporting only a subset of versions in the next release of pynetlogo and make this clear in the documentation.

**Comment by EwoutH** [comment]
I can understand. You could just support the latest one, and make clear in the documentation if you want to use an older NetLogo version you use an older PyNetLogo version.

Or dropping support for 5.x and 6.0 would also help a lot, since there aren't that many changes after 6.1.

On thing to also check is that NetLogo 6.3 is build and ships with Java 17, instead of Java 8. See https://github.com/NetLogo/NetLogo/pull/2045.

**Comment by quaquel** [comment]
I currently do not have easy access to a windows or linux machine. Can you check the directory structure for the extensions folder on either of these installs? Specifically, is there an app subdirectory?

see also https://github.com/quaquel/pyNetLogo/blob/1df036e3b2b4a386a5e48b562fc5c2047191c0c6/src/pynetlogo/core.py#L250-L258

**Comment by EwoutH** [comment]
<details><summary>Here is the full tree (on Winows)</summary>

```
C:\Program Files\NetLogo 6.3.0>tree
Folder PATH listing
Volume serial number is E49B-5C32
C:.
├───app
├───behaviorsearch
│   ├───documentation
│   │   └───img
│   ├───examples
│   └───resources
├───docs
│   ├───dict
│   └───images
│       ├───3d
│       ├───behaviorspace
│       ├───codetab
│       ├───extension-manager
│       ├───gogo
│       ├───hubnet
│       ├───infotab
│       ├───interface
│       ├───interfacetab
│       ├───modelingcommons
│       ├───programming
│       ├───sample
│       ├───shapes
│       ├───systemdynamics
│       ├───transition
│       ├───tutorial1
│       ├───tutorial2
│       ├───tutorial3
│       └───whatis
├───extensions
│   └───.bundled
│       ├───arduino
│       ├───array
│       ├───bitmap
│       ├───csv
│       ├───gis
│       ├───gogo
│       ├───ls
│       ├───matrix
│       ├───nw
│       ├───palette
│       ├───profiler
│       ├───py
│       ├───r
│       │   └───models
│       ├───rnd
│       ├───sample
│       ├───sample-scala
│       ├───sound
│       ├───table
│       ├───time
│       ├───vid
│       └───view2.5d
├───Mathematica Link
├───models
│   ├───3D
│   │   ├───Code Examples
│   │   └───Sample Models
│   │       └───GasLab
│   ├───Alternative Visualizations
│   ├───Code Examples
│   │   ├───Extensions Examples
│   │   │   ├───csv
│   │   │   ├───gis
│   │   │   │   └───data
│   │   │   ├───gogo
│   │   │   ├───ls
│   │   │   ├───matrix
│   │   │   ├───nw
│   │   │   ├───palette
│   │   │   ├───profiler
│   │   │   ├───py
│   │   │   ├───rnd
│   │   │   ├───sound
│   │   │   │   └───Beats
│   │   │   ├───table
│   │   │   ├───time
│   │   │   ├───vid
│   │   │   └───view2.5d
│   │   └───Perspective Demos
│   ├───Curricular Models
│   │   ├───BEAGLE Evolution
│   │   │   ├───EACH
│   │   │   └───HubNet Activities
│   │   ├───Connected Chemistry
│   │   ├───CT-STEM
│   │   ├───epiDEM
│   │   ├───GenEvo
│   │   ├───Lattice Land
│   │   ├───MaterialSim
│   │   ├───Mind the Gap
│   │   ├───ModelSim
│   │   │   ├───Evolution
│   │   │   └───Population Biology
│   │   ├───NIELS
│   │   ├───PNoM
│   │   ├───ProbLab
│   │   └───Urban Suite
│   ├───HubNet Activities
│   │   ├───Code Examples
│   │   └───Unverified
│   ├───IABM Textbook
│   │   ├───chapter 0
│   │   ├───chapter 1
│   │   ├───chapter 2
│   │   ├───chapter 3
│   │   │   ├───DLA Extensions
│   │   │   ├───El Farol Extensions
│   │   │   ├───Fire Extensions
│   │   │   └───Segregation Extensions
│   │   ├───chapter 4
│   │   ├───chapter 5
│   │   ├───chapter 6
│   │   ├───chapter 7
│   │   └───chapter 8
│   │       ├───arduino-example-sketch
│   │       └───data
│   └───Sample Models
│       ├───Art
│       ├───Biology
│       │   ├───CRISPR
│       │   ├───Evolution
│       │   │   └───Genetic Drift
│       │   └───Unverified
│       ├───Chemistry & Physics
│       │   ├───Chemical Reactions
│       │   │   └───Acids and Bases
│       │   │       └───Unverified
│       │   ├───Diffusion Limited Aggregation
│       │   ├───GasLab
│       │   │   └───Unverified
│       │   ├───Materials Science
│       │   │   └───Crystallization
│       │   ├───Mechanics
│       │   │   └───Unverified
│       │   ├───Radioactivity
│       │   │   └───Unverified
│       │   ├───Unverified
│       │   └───Waves
│       │       └───Unverified
│       ├───Computer Science
│       │   ├───Cellular Automata
│       │   │   └───CA 1D Simple Examples
│       │   ├───Particle Systems
│       │   └───Unverified
│       ├───Earth Science
│       │   └───Unverified
│       ├───Games
│       │   └───Unverified
│       ├───Mathematics
│       │   ├───Fractals
│       │   ├───Probability
│       │   │   ├───ProbLab
│       │   │   │   └───Unverified
│       │   │   └───Unverified
│       │   └───Unverified
│       ├───Networks
│       ├───Philosophy
│       ├───Psychology
│       ├───Social Science
│       │   ├───Distribution Center Discrete Event Simulator
│       │   ├───Economics
│       │   │   ├───Sugarscape
│       │   │   └───Unverified
│       │   ├───Prisoner's Dilemma
│       │   └───Unverified
│       │       └───data
│       └───System Dynamics
│           └───Unverified
├───natives
│   ├───windows-amd64
│   └───windows-i586
└───runtime
    ├───bin
    │   ├───client
    │   └───server
    ├───conf
    │   ├───management
    │   └───security
    │       └───policy
    │           ├───limited
    │           └───unlimited
    ├───legal
    │   ├───java.base
    │   ├───java.compiler
    │   ├───java.datatransfer
    │   ├───java.desktop
    │   ├───java.instrument
    │   ├───java.logging
    │   ├───java.management
    │   ├───java.management.rmi
    │   ├───java.naming
    │   ├───java.net.http
    │   ├───java.prefs
    │   ├───java.rmi
    │   ├───java.scripting
    │   ├───java.security.jgss
    │   ├───java.security.sasl
    │   ├───java.smartcardio
    │   ├───java.sql
    │   ├───java.sql.rowset
    │   ├───java.transaction.xa
    │   ├───java.xml
    │   ├───java.xml.crypto
    │   ├───javafx.base
    │   ├───javafx.controls
    │   ├───javafx.fxml
    │   ├───javafx.graphics
    │   ├───javafx.media
    │   ├───javafx.swing
    │   ├───javafx.web
    │   ├───jdk.accessibility
    │   ├───jdk.attach
    │   ├───jdk.charsets
    │   ├───jdk.compiler
    │   ├───jdk.crypto.cryptoki
    │   ├───jdk.crypto.ec
    │   ├───jdk.crypto.mscapi
    │   ├───jdk.dynalink
    │   ├───jdk.editpad
    │   ├───jdk.httpserver
    │   ├───jdk.incubator.foreign
    │   ├───jdk.incubator.vector
    │   ├───jdk.internal.ed
    │   ├───jdk.internal.jvmstat
    │   ├───jdk.internal.le
    │   ├───jdk.internal.opt
    │   ├───jdk.jartool
    │   ├───jdk.javadoc
    │   ├───jdk.jconsole
    │   ├───jdk.jdeps
    │   ├───jdk.jdi
    │   ├───jdk.jdwp.agent
    │   ├───jdk.jfr
    │   ├───jdk.jlink
    │   ├───jdk.jpackage
    │   ├───jdk.jshell
    │   ├───jdk.jsobject
    │   ├───jdk.jstatd
    │   ├───jdk.localedata
    │   ├───jdk.management
    │   ├───jdk.management.agent
    │   ├───jdk.management.jfr
    │   ├───jdk.naming.dns
    │   ├───jdk.naming.rmi
    │   ├───jdk.net
    │   ├───jdk.nio.mapmode
    │   ├───jdk.random
    │   ├───jdk.sctp
    │   ├───jdk.security.auth
    │   ├───jdk.security.jgss
    │   ├───jdk.unsupported
    │   ├───jdk.unsupported.desktop
    │   ├───jdk.xml.dom
    │   └───jdk.zipfs
    └───lib
        ├───jfr
        └───security
```
</details>

**Comment by quaquel** [comment]
Then for 6.3 it is identical to Mac. So easy to fix.

Now just have to check the structure for older versions of netlogo

**Comment by quaquel** [comment]
Just checked on Windows for 6.1. The extension folder has been moved in 6.3. So the problem is not the `/.bundeld` but the move from the app folder to the main netlogo folder.

My current idea is just to write some code that crawls netlogo_home for the extension folder. This will work across versions and platforms.

**Comment by EwoutH** [comment]
Sounds like a good idea. Maybe defining the path using wildcards (`*`) and recursive wildcards(`**`) might also work.

**Comment by EwoutH** [comment]
Good news and bad news:
 - The `UserWarning: could not find default NetLogo extensions folder. Extensions not available` is gone, it looks like it finds them correctly.
 - Both with and before this commit, it can't find the NetLogoLinkV63.NetLogoLink class.
  ```
   Traceback (most recent call last):
    File "C:\Users\Ewout\Documents\GitHub\SEN9120-ABC\notebooks\run_sensitivity.py", line 41, in <module>
      netlogo = pynetlogo.NetLogoLink(gui=gui)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Ewout\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-1\231.8109.91\jbr\bin\src\pynetlogo\src\pynetlogo\core.py", line 275, in __init__
      link = jpype.JClass(class_name[self.netlogo_version])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Ewout\AppData\Local\Programs\Python\Python311\Lib\site-packages\jpype\_jclass.py", line 99, in __new__
      return _jpype._getClass(jc)
             ^^^^^^^^^^^^^^^^^^^^
  TypeError: Class NetLogoLinkV63.NetLogoLink is not found
  ```

So af44c1d does what it should do, but somewhere before that something else broke.

**Comment by EwoutH** [comment]
So I tried to bisect this, and I found some inconsistent behaviour, but it seems 287dbe2c4cd995878c65d955dc855284d9a89899 generally works. So it's most likely some change after that.

**Comment by quaquel** [comment]
I pushed a substantial update.

1. dropped supported for 6.0. 
2. recompiled the jar file of 6.3 but with compatibility for java 8 and newer. This means the jar is compatible with NetLogo 6.1 and newer.
3. shifted to more modern import functionality in jpype
4. substantial simplification of code because there is no longer any need to check the NetLogo version and load the appropriate jar files.
5. tested it against 6.3 on an m1 mac and against 6.1, 6.2, and 6.3 under windows. It all works. I can't test against 6.1 and 6.2 and the m1 mac for obscure reasons with mac security settings. 6.1 and 6.2 just won't work, even standalone. 

Let me know whether this commit resolves the weird import error.

**Comment by quaquel** [comment]
If you have a chance to test this, that would be great. We are then basically ready for the 0.5 release.

**Comment by EwoutH** [comment]
Yes, on my system this works and installs properly, without errors or warnings!
